services:
  #django app
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - django_redis
      - django_db

#REDIS
  django_redis:
    container_name: django_redis
    image: redis
    ports:
      - "6379:6379"

#database
  django_db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .db_data:/var/lib/postgresql/
    


#celery
  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - django_db
      - django_redis