# Generated by Django 4.2.16 on 2025-02-26 16:03

import apps.blog.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', storage=core.storage_backends.PublicMediaStorage(), upload_to=apps.blog.models.blog_thumbnail_directory),
            preserve_default=False,
        ),
    ]
