# Generated by Django 4.2.16 on 2025-02-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_heading_post_alter_postaanalytics_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostAanalytics',
            new_name='PostAnalytics',
        ),
    ]
